function W = WeightGenerate(N,P,w0)
%% WEIGHTGENERATE generate weight on a pseudo-polar grid
%
%% Description
%  W = WEIGHTGENERATE(N,P,W0) generate a weight matrix on a pseudo-polar
%  grid for an image of size N. P is the basis functions generated by
%  routine  BASISFUNCTION. W0 is the weight constant in terms of basis
%  function computed by FINDWEIGHT.
%
%% Examples
%    N = 64; R = 2; Choice = 1;
%    P = basisFunction(N,R,Choice);
%    w = loadw(N,R,Choice);
%    W = WeightGenerate(N,P,w0);
%
%% See also BASISFUNCTION, FINDWEIGHT, LOADW

%% Copyright
% Copyright (C) 2011. Xiaosheng Zhuang, University of Osnabrueck

LQ = size(P,2);
if LQ ~= length(w0)
    error('number of basis functions and weights not match');
end

RN1 = size(P,1);
d1 = 2;
d2 = (RN1/d1)/(N+1);
d3 = N+1;

w1 = P*w0;
w2 = reshape(w1,d1,d2,d3);
W  = w2*prod([d1,d2,d3]);
end