%% WEIGHTGENERATE 
% generate weight on a pseudo-polar grid
%
%% Description
%  W = WEIGHTGENERATE(N,P,W0) generate a weight matrix on a pseudo-polar
%  grid for an image of size N. P is the basis functions generated by
%  routine  BASISFUNCTION. W0 is the weight constant in terms of basis
%  function computed by FINDWEIGHT.
%
%% Examples
    N = 64; R = 2; Choice = 1;
    P = basisFunction(N,R,Choice);
    w = loadw(N,R,Choice);
    W = WeightGenerate(N,P,w0);

%% See also
% <basisFunction_help.html BASISFUNCTION>.
% <condW_help.html CONDW>,
% <errorW_help.html ERRORW>,
% <errorW_random_help.html ERRORW_RANDOM>,
% <findWeight_help.html FINDWEIGHT>,
% <loadW_help.html LOADW>,
% <saveW_help.html SAVEW>,

%% Copyright
% Copyright (C) 2011. Xiaosheng Zhuang, University of Osnabrueck
